In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
df = pd.read_csv('AmesHousing.csv')
df.sample(2)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
2461,2462,528477010,60,FV,100.0,13162,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2006,New,Partial,405749
2428,2429,528228575,120,RL,53.0,3982,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,10,2006,New,Partial,264561

In [74]:
df.shape

(2930, 82)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [76]:
print(df.columns)

Index(['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'Sale Condition', 'SalePrice'],
      dtype='object')

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [78]:
num_cols=df.select_dtypes(include=['int64','float64']).columns
print("Numerical columns:", len(num_cols))
print(num_cols)

Numerical columns: 39
Index(['Order', 'PID', 'MS SubClass', 'Lot Frontage', 'Lot Area',
       'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add',
       'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF',
       'Total Bsmt SF', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd',
       'Fireplaces', 'Garage Yr Blt', 'Garage Cars', 'Garage Area',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold',
       'SalePrice'],
      dtype='object')

In [79]:
cat_cols = df.select_dtypes(include=['object', 'category']).columns
print("Categorical columns:", len(cat_cols))
print(cat_cols)

Categorical columns: 43
Index(['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour',
       'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl',
       'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating', 'Heating QC',
       'Central Air', 'Electrical', 'Kitchen Qual', 'Functional',
       'Fireplace Qu', 'Garage Type', 'Garage Finish', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Pool QC', 'Fence', 'Misc Feature',
       'Sale Type', 'Sale Condition'],
      dtype='object')

In [80]:
threshold = 0.95

dominant_cols = []

for col in cat_cols:
    top_freq = df[col].value_counts(normalize=True, dropna=False).values[0]
    
    if top_freq > threshold:
        dominant_cols.append((col, top_freq))


for col, freq in dominant_cols:
    print(f"{col}: {freq:.2f}")

Street: 1.00
Utilities: 1.00
Land Slope: 0.95
Condition 2: 0.99
Roof Matl: 0.99
Heating: 0.98
Pool QC: 1.00
Misc Feature: 0.96

In [81]:
dominant_cols_names = [col for col, freq in dominant_cols]
dominant_cols_names

['Street',
 'Utilities',
 'Land Slope',
 'Condition 2',
 'Roof Matl',
 'Heating',
 'Pool QC',
 'Misc Feature']

In [82]:
cat_cols = cat_cols.drop(dominant_cols_names)

In [83]:
cat_cols

Index(['MS Zoning', 'Alley', 'Lot Shape', 'Land Contour', 'Lot Config',
       'Neighborhood', 'Condition 1', 'Bldg Type', 'House Style', 'Roof Style',
       'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating QC', 'Central Air',
       'Electrical', 'Kitchen Qual', 'Functional', 'Fireplace Qu',
       'Garage Type', 'Garage Finish', 'Garage Qual', 'Garage Cond',
       'Paved Drive', 'Fence', 'Sale Type', 'Sale Condition'],
      dtype='object')

In [84]:
num_cols

Index(['Order', 'PID', 'MS SubClass', 'Lot Frontage', 'Lot Area',
       'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add',
       'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF',
       'Total Bsmt SF', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd',
       'Fireplaces', 'Garage Yr Blt', 'Garage Cars', 'Garage Area',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold',
       'SalePrice'],
      dtype='object')

In [85]:
df[cat_cols].nunique().sort_values()

Alley              2
Central Air        2
Paved Drive        3
Garage Finish      3
Mas Vnr Type       4
Lot Shape          4
Land Contour       4
Exter Qual         4
Bsmt Exposure      4
Fence              4
Heating QC         5
Bsmt Cond          5
Bsmt Qual          5
Exter Cond         5
Bldg Type          5
Electrical         5
Garage Qual        5
Garage Cond        5
Kitchen Qual       5
Fireplace Qu       5
Lot Config         5
BsmtFin Type 2     6
Roof Style         6
BsmtFin Type 1     6
Garage Type        6
Foundation         6
Sale Condition     6
MS Zoning          7
House Style        8
Functional         8
Condition 1        9
Sale Type         10
Exterior 1st      16
Exterior 2nd      17
Neighborhood      28
dtype: int64

In [86]:
df[num_cols].isnull().sum().sort_values(ascending=False)

Lot Frontage       490
Garage Yr Blt      159
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
BsmtFin SF 2         1
Total Bsmt SF        1
Garage Cars          1
Garage Area          1
Bsmt Unf SF          1
BsmtFin SF 1         1
Order                0
PID                  0
Lot Area             0
MS SubClass          0
Overall Cond         0
Overall Qual         0
1st Flr SF           0
2nd Flr SF           0
Gr Liv Area          0
Year Built           0
Low Qual Fin SF      0
Year Remod/Add       0
Bedroom AbvGr        0
Half Bath            0
Full Bath            0
Kitchen AbvGr        0
Fireplaces           0
TotRms AbvGrd        0
Wood Deck SF         0
Open Porch SF        0
Enclosed Porch       0
3Ssn Porch           0
Screen Porch         0
Pool Area            0
Misc Val             0
Mo Sold              0
Yr Sold              0
SalePrice            0
dtype: int64

In [87]:
corr = df.corr(numeric_only=True)["SalePrice"].sort_values(ascending=False)
print(corr)

SalePrice          1.000000
Overall Qual       0.799262
Gr Liv Area        0.706780
Garage Cars        0.647877
Garage Area        0.640401
Total Bsmt SF      0.632280
1st Flr SF         0.621676
Year Built         0.558426
Full Bath          0.545604
Year Remod/Add     0.532974
Garage Yr Blt      0.526965
Mas Vnr Area       0.508285
TotRms AbvGrd      0.495474
Fireplaces         0.474558
BsmtFin SF 1       0.432914
Lot Frontage       0.357318
Wood Deck SF       0.327143
Open Porch SF      0.312951
Half Bath          0.285056
Bsmt Full Bath     0.276050
2nd Flr SF         0.269373
Lot Area           0.266549
Bsmt Unf SF        0.182855
Bedroom AbvGr      0.143913
Screen Porch       0.112151
Pool Area          0.068403
Mo Sold            0.035259
3Ssn Porch         0.032225
BsmtFin SF 2       0.005891
Misc Val          -0.015691
Yr Sold           -0.030569
Order             -0.031408
Bsmt Half Bath    -0.035835
Low Qual Fin SF   -0.037660
MS SubClass       -0.085092
Overall Cond      -0.101697
Kitchen AbvGr     -0.119814
Enclosed Porch    -0.128787
PID               -0.246521
Name: SalePrice, dtype: float64

In [88]:
print("Top positive correlations:")
print(corr.head(10))

print("\nTop negative correlations:")

print(corr.tail(10))

Top positive correlations:
SalePrice         1.000000
Overall Qual      0.799262
Gr Liv Area       0.706780
Garage Cars       0.647877
Garage Area       0.640401
Total Bsmt SF     0.632280
1st Flr SF        0.621676
Year Built        0.558426
Full Bath         0.545604
Year Remod/Add    0.532974
Name: SalePrice, dtype: float64

Top negative correlations:
Misc Val          -0.015691
Yr Sold           -0.030569
Order             -0.031408
Bsmt Half Bath    -0.035835
Low Qual Fin SF   -0.037660
MS SubClass       -0.085092
Overall Cond      -0.101697
Kitchen AbvGr     -0.119814
Enclosed Porch    -0.128787
PID               -0.246521
Name: SalePrice, dtype: float64

In [89]:
df[num_cols].isnull().sum().sort_values(ascending=False)

Lot Frontage       490
Garage Yr Blt      159
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
BsmtFin SF 2         1
Total Bsmt SF        1
Garage Cars          1
Garage Area          1
Bsmt Unf SF          1
BsmtFin SF 1         1
Order                0
PID                  0
Lot Area             0
MS SubClass          0
Overall Cond         0
Overall Qual         0
1st Flr SF           0
2nd Flr SF           0
Gr Liv Area          0
Year Built           0
Low Qual Fin SF      0
Year Remod/Add       0
Bedroom AbvGr        0
Half Bath            0
Full Bath            0
Kitchen AbvGr        0
Fireplaces           0
TotRms AbvGrd        0
Wood Deck SF         0
Open Porch SF        0
Enclosed Porch       0
3Ssn Porch           0
Screen Porch         0
Pool Area            0
Misc Val             0
Mo Sold              0
Yr Sold              0
SalePrice            0
dtype: int64

In [90]:
df['Garage Yr Blt'] = df['Garage Yr Blt'].fillna(0)
df['Garage Cars'] = df['Garage Cars'].fillna(0)
df['Garage Area'] = df['Garage Area'].fillna(0)

In [91]:
df['Lot Frontage'] = df['Lot Frontage'].fillna(df['Lot Frontage'].median())

In [92]:
df[num_cols].isnull().sum().sort_values(ascending=False)

Mas Vnr Area       23
Bsmt Full Bath      2
Bsmt Half Bath      2
BsmtFin SF 1        1
Bsmt Unf SF         1
BsmtFin SF 2        1
Total Bsmt SF       1
Overall Cond        0
Overall Qual        0
Lot Area            0
Lot Frontage        0
MS SubClass         0
PID                 0
Order               0
Year Remod/Add      0
1st Flr SF          0
Year Built          0
Low Qual Fin SF     0
2nd Flr SF          0
Gr Liv Area         0
Full Bath           0
Half Bath           0
Bedroom AbvGr       0
Kitchen AbvGr       0
TotRms AbvGrd       0
Fireplaces          0
Garage Yr Blt       0
Garage Cars         0
Garage Area         0
Wood Deck SF        0
Open Porch SF       0
Enclosed Porch      0
3Ssn Porch          0
Screen Porch        0
Pool Area           0
Misc Val            0
Mo Sold             0
Yr Sold             0
SalePrice           0
dtype: int64

In [93]:
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [94]:
df[num_cols].isnull().sum().sort_values(ascending=False)

Order              0
PID                0
MS SubClass        0
Lot Frontage       0
Lot Area           0
Overall Qual       0
Overall Cond       0
Year Built         0
Year Remod/Add     0
Mas Vnr Area       0
BsmtFin SF 1       0
BsmtFin SF 2       0
Bsmt Unf SF        0
Total Bsmt SF      0
1st Flr SF         0
2nd Flr SF         0
Low Qual Fin SF    0
Gr Liv Area        0
Bsmt Full Bath     0
Bsmt Half Bath     0
Full Bath          0
Half Bath          0
Bedroom AbvGr      0
Kitchen AbvGr      0
TotRms AbvGrd      0
Fireplaces         0
Garage Yr Blt      0
Garage Cars        0
Garage Area        0
Wood Deck SF       0
Open Porch SF      0
Enclosed Porch     0
3Ssn Porch         0
Screen Porch       0
Pool Area          0
Misc Val           0
Mo Sold            0
Yr Sold            0
SalePrice          0
dtype: int64

In [95]:
df = df.drop(['Order', 'PID'], axis=1)

In [96]:
num_cols

Index(['Order', 'PID', 'MS SubClass', 'Lot Frontage', 'Lot Area',
       'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add',
       'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF',
       'Total Bsmt SF', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd',
       'Fireplaces', 'Garage Yr Blt', 'Garage Cars', 'Garage Area',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold',
       'SalePrice'],
      dtype='object')

In [97]:
num_cols = [col for col in num_cols if col not in ['Order', 'PID']]

In [98]:
num_cols

['MS SubClass',
 'Lot Frontage',
 'Lot Area',
 'Overall Qual',
 'Overall Cond',
 'Year Built',
 'Year Remod/Add',
 'Mas Vnr Area',
 'BsmtFin SF 1',
 'BsmtFin SF 2',
 'Bsmt Unf SF',
 'Total Bsmt SF',
 '1st Flr SF',
 '2nd Flr SF',
 'Low Qual Fin SF',
 'Gr Liv Area',
 'Bsmt Full Bath',
 'Bsmt Half Bath',
 'Full Bath',
 'Half Bath',
 'Bedroom AbvGr',
 'Kitchen AbvGr',
 'TotRms AbvGrd',
 'Fireplaces',
 'Garage Yr Blt',
 'Garage Cars',
 'Garage Area',
 'Wood Deck SF',
 'Open Porch SF',
 'Enclosed Porch',
 '3Ssn Porch',
 'Screen Porch',
 'Pool Area',
 'Misc Val',
 'Mo Sold',
 'Yr Sold',
 'SalePrice']

In [99]:
num_cols = [col for col in num_cols if col not in ['SalePrice']]

In [100]:
x = df.drop('SalePrice', axis=1)
y = df['SalePrice']

In [101]:
cat_cols = [col for col in X.columns if col not in num_cols]

In [102]:
df[cat_cols].isnull().sum().sort_values(ascending=False)

Pool QC           2917
Misc Feature      2824
Alley             2732
Fence             2358
Mas Vnr Type      1775
Fireplace Qu      1422
Garage Cond        159
Garage Qual        159
Garage Finish      159
Garage Type        157
Bsmt Exposure       83
BsmtFin Type 2      81
BsmtFin Type 1      80
Bsmt Qual           80
Bsmt Cond           80
Electrical           1
Condition 1          0
Condition 2          0
Lot Shape            0
Street               0
MS Zoning            0
Neighborhood         0
Land Slope           0
Lot Config           0
Utilities            0
Land Contour         0
Roof Style           0
Heating              0
Exter Cond           0
Foundation           0
House Style          0
Roof Matl            0
Exterior 1st         0
Exterior 2nd         0
Exter Qual           0
Bldg Type            0
Heating QC           0
Central Air          0
Kitchen Qual         0
Functional           0
Paved Drive          0
Sale Type            0
Sale Condition       0
dtype: int64

In [103]:
none_cols = [
    "Pool QC", "Misc Feature", "Alley", "Fence",
    "Fireplace Qu",
    "Garage Cond", "Garage Qual", "Garage Finish", "Garage Type",
    "Bsmt Exposure", "BsmtFin Type 2", "BsmtFin Type 1",
    "Bsmt Qual", "Bsmt Cond",
]

df[none_cols] = df[none_cols].fillna("None")

In [104]:
df[cat_cols].isnull().sum().sort_values(ascending=False)

Mas Vnr Type      1775
Electrical           1
MS Zoning            0
Lot Shape            0
Land Contour         0
Utilities            0
Lot Config           0
Land Slope           0
Neighborhood         0
Street               0
Alley                0
Condition 2          0
Condition 1          0
Roof Style           0
Bldg Type            0
Roof Matl            0
Exterior 1st         0
Exterior 2nd         0
House Style          0
Exter Cond           0
Foundation           0
Bsmt Qual            0
Bsmt Cond            0
Bsmt Exposure        0
BsmtFin Type 1       0
BsmtFin Type 2       0
Exter Qual           0
Heating              0
Heating QC           0
Central Air          0
Kitchen Qual         0
Functional           0
Fireplace Qu         0
Garage Type          0
Garage Finish        0
Garage Qual          0
Garage Cond          0
Paved Drive          0
Pool QC              0
Fence                0
Misc Feature         0
Sale Type            0
Sale Condition       0
dtype: int64

In [105]:
mode_cols = ["Mas Vnr Type", "Electrical"]

for col in mode_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [106]:
df[cat_cols].isnull().sum().sort_values(ascending=False)

MS Zoning         0
Street            0
Alley             0
Lot Shape         0
Land Contour      0
Utilities         0
Lot Config        0
Land Slope        0
Neighborhood      0
Condition 1       0
Condition 2       0
Bldg Type         0
House Style       0
Roof Style        0
Roof Matl         0
Exterior 1st      0
Exterior 2nd      0
Mas Vnr Type      0
Exter Qual        0
Exter Cond        0
Foundation        0
Bsmt Qual         0
Bsmt Cond         0
Bsmt Exposure     0
BsmtFin Type 1    0
BsmtFin Type 2    0
Heating           0
Heating QC        0
Central Air       0
Electrical        0
Kitchen Qual      0
Functional        0
Fireplace Qu      0
Garage Type       0
Garage Finish     0
Garage Qual       0
Garage Cond       0
Paved Drive       0
Pool QC           0
Fence             0
Misc Feature      0
Sale Type         0
Sale Condition    0
dtype: int64

In [107]:
print(df.isnull().sum().sort_values(ascending=False).head(10))

MS SubClass     0
MS Zoning       0
Lot Frontage    0
Lot Area        0
Street          0
Alley           0
Lot Shape       0
Land Contour    0
Utilities       0
Lot Config      0
dtype: int64

In [108]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

preprocessor=ColumnTransformer([
    ('num',StandardScaler(),num_cols),
    ('cat',OneHotEncoder(handle_unknown="ignore"),cat_cols)
])

In [109]:
df[num_cols]

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold
0,20,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,...,528.0,210,62,0,0,0,0,0,5,2010
1,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,730.0,140,0,0,0,120,0,0,6,2010
2,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,312.0,393,36,0,0,0,0,12500,6,2010
3,20,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,...,522.0,0,0,0,0,0,0,0,4,2010
4,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,482.0,212,34,0,0,0,0,0,3,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,80,37.0,7937,6,6,1984,1984,0.0,819.0,0.0,...,588.0,120,0,0,0,0,0,0,3,2006
2926,20,68.0,8885,5,5,1983,1983,0.0,301.0,324.0,...,484.0,164,0,0,0,0,0,0,6,2006
2927,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,0.0,80,32,0,0,0,0,700,7,2006
2928,20,77.0,10010,5,5,1974,1975,0.0,1071.0,123.0,...,418.0,240,38,0,0,0,0,0,4,2006
2929,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,650.0,190,48,0,0,0,0,0,11,2006

In [110]:
X_transformed = preprocessor.fit_transform(x)

In [111]:
X_transformed

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 231470 stored elements and shape (2930, 319)>

In [112]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_transformed,y,random_state=34,train_size=0.8)

In [113]:
x_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 185176 stored elements and shape (2344, 319)>

In [114]:
x_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 46294 stored elements and shape (586, 319)>

In [115]:
y_test.shape

(586,)

In [116]:
from sklearn.linear_model import LinearRegression

In [117]:
lr=LinearRegression()

In [118]:
lr.fit(x_train,y_train)

LinearRegression()

In [119]:
y_pred_linear=lr.predict(x_test)
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

print("MAE:",mean_absolute_error(y_pred_linear,y_test))
print("MSE:",mean_squared_error(y_pred_linear,y_test))
print("R2:",r2_score(y_pred_linear,y_test))

MAE: 15687.80736461713
MSE: 864868361.6008278
R2: 0.861708185604882

In [68]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_transformed,y,random_state=34,train_size=0.8)

In [69]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [146]:
from sklearn.linear_model import Ridge,Lasso,ElasticNet

ridgemodel=Ridge(alpha=0.5)
lassomodel=Lasso(alpha=100)
elasticnetmodel=ElasticNet(alpha=0.01,l1_ratio=0.5)


ridgemodel.fit(x_train,y_train)
lassomodel.fit(x_train,y_train)
elasticnetmodel.fit(x_train,y_train)

c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.233e+09, tolerance: 1.516e+09
  model = cd_fast.sparse_enet_coordinate_descent(

ElasticNet(alpha=0.01)

In [135]:
y_pred_ridge=ridgemodel.predict(x_test)
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

print("MAE:",mean_absolute_error(y_pred_ridge,y_test))
print("MSE:",mean_squared_error(y_pred_ridge,y_test))
print("R2:",r2_score(y_pred_ridge,y_test))

MAE: 15775.433576979403
MSE: 817843141.3167771
R2: 0.8664365911032992

In [143]:
y_pred_lasso=lassomodel.predict(x_test)
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

print("MAE:",mean_absolute_error(y_pred_lasso,y_test))
print("MSE:",mean_squared_error(y_pred_lasso,y_test))
print("R2:",r2_score(y_pred_lasso,y_test))

MAE: 15497.924215514642
MSE: 776149397.0805389
R2: 0.8674953380320014

In [147]:
y_pred_elastic=elasticnetmodel.predict(x_test)
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

print("MAE:",mean_absolute_error(y_pred_elastic,y_test))
print("MSE:",mean_squared_error(y_pred_elastic,y_test))
print("R2:",r2_score(y_pred_elastic,y_test))

MAE: 15907.00453028534
MSE: 779641070.8418592
R2: 0.8676331091962814

In [150]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.model_selection import GridSearchCV

alphas = {'alpha': [0.01, 0.1, 1, 10, 50, 100, 200, 500]}

# Ridge
ridge_grid = GridSearchCV(Ridge(), alphas, cv=5, scoring='r2')
ridge_grid.fit(x_train, y_train)
print("Best Ridge alpha:", ridge_grid.best_params_)
print("Best Ridge CV R2:", round(ridge_grid.best_score_, 4))

# Lasso — add max_iter to fix ConvergenceWarning
lasso_grid = GridSearchCV(Lasso(max_iter=10000), alphas, cv=5, scoring='r2')
lasso_grid.fit(x_train, y_train)
print("\nBest Lasso alpha:", lasso_grid.best_params_)
print("Best Lasso CV R2:", round(lasso_grid.best_score_, 4))

# ElasticNet — also add max_iter
en_params = {
    'alpha':    [0.01, 0.1, 1, 10, 50],
    'l1_ratio': [0.2, 0.5, 0.7, 0.9]
}
en_grid = GridSearchCV(ElasticNet(max_iter=10000), en_params, cv=5, scoring='r2')
en_grid.fit(x_train, y_train)
print("\nBest ElasticNet params:", en_grid.best_params_)
print("Best ElasticNet CV R2:", round(en_grid.best_score_, 4))

# Final evaluation on test set with best models
from sklearn.metrics import r2_score, mean_absolute_error

for name, grid in [('Ridge', ridge_grid), ('Lasso', lasso_grid), ('ElasticNet', en_grid)]:
    y_pred = grid.best_estimator_.predict(x_test)
    print(f"\n{name} Test | MAE: ${mean_absolute_error(y_test, y_pred):,.0f} | R2: {r2_score(y_test, y_pred):.4f}")

Best Ridge alpha: {'alpha': 10}
Best Ridge CV R2: 0.8545

c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.162e+11, tolerance: 1.230e+09
  model = cd_fast.sparse_enet_coordinate_descent(
c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.198e+11, tolerance: 1.196e+09
  model = cd_fast.sparse_enet_coordinate_descent(
c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.305e+11, tolerance: 1.216e+09
  model = cd_fast.sparse_enet_coordinate_descent(
c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.936e+11, tolerance: 1.254e+09
  model = cd_fast.sparse_enet_coordinate_descent(
c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.001e+11, tolerance: 1.167e+09
  model = cd_fast.sparse_enet_coordinate_descent(
c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.860e+11, tolerance: 1.230e+09
  model = cd_fast.sparse_enet_coordinate_descent(
c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.651e+11, tolerance: 1.196e+09
  model = cd_fast.sparse_enet_coordinate_descent(
c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.461e+10, tolerance: 1.216e+09
  model = cd_fast.sparse_enet_coordinate_descent(
c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.906e+10, tolerance: 1.254e+09
  model = cd_fast.sparse_enet_coordinate_descent(
c:\Users\rayph\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:675: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.676e+11, tolerance: 1.167e+09
  model = cd_fast.sparse_enet_coordinate_descent(

Best Lasso alpha: {'alpha': 50}
Best Lasso CV R2: 0.8661

Best ElasticNet params: {'alpha': 0.01, 'l1_ratio': 0.2}
Best ElasticNet CV R2: 0.8544

Ridge Test | MAE: $15,911 | R2: 0.8704

Lasso Test | MAE: $15,515 | R2: 0.8643

ElasticNet Test | MAE: $15,877 | R2: 0.8709

In [ ]:
from sklearn.poly import poly