In [4]:
from pandas_profiling import ProfileReport
import pandas as pd
import seaborn as sns

In [5]:
df=sns.load_dataset('tips')

In [6]:
df.sample(2)

     total_bill   tip   sex smoker  day    time  size
207       38.73  3.00  Male    Yes  Sat  Dinner     4
8         15.04  1.96  Male     No  Sun  Dinner     2

In [7]:
prof=ProfileReport(df)
prof.to_file(output_file='analysis.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 7/7 [00:00<00:00, 666.03it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
df2=sns.load_dataset('titanic')

In [9]:
df2.sample(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
496,1,1,female,54.0,1,0,78.2667,C,First,woman,False,D,Cherbourg,yes,False
486,1,1,female,35.0,1,0,90.0000,S,First,woman,False,C,Southampton,yes,False

In [12]:
prof2=ProfileReport(df2)
prof.to_file(output_file='newone.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]